import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from './components/navBar'
import Jumbotron from './components/jumbotron'
import Products from './components/products'
import Store from './components/store'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <main className={`${styles.main}`}>
        <Jumbotron />
        <Products />
        <Store />
      </main>
    </>
  )
}
